# The following are settings of the button in the upper-right corner.

github: "https://4ading.com/"
githubToolTip: "主站"

footer: true

# the following are favicon settings.
# You can visit https://realfavicongenerator.net/ for more information and generate your favicon and apply it for your site.

favicon:
  favicon: "/favicon.ico"
  appleTouchIcon: "/img/apple-touch-icon.png"
  icon32: "/img/favicon-32x32.png"
  icon16: "/img/favicon-16x16.png"
  manifest: "/img/site.webmanifest"
  maskIcon: "/img/safari-pinned-tab.svg"
  themeColor: "#F1F3F5"